spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/assignmentDb
    username: devUser
    password: devPass

  # Hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#In memory default users configuration
security:
  users:
    admin:
      username: admin
      password: "@dm1n"
      role: ADMIN
    user:
      username: user
      password: "4s3r"
      role: USER

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
